server:
  http_listen_port: 9080
  #grpc_listen: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push


# Quais lugares estão armazenados os arquivos de logs
scrape_configs:
- job_name: system
  static_configs:
  - targets:
    - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  - targets:
    - localhost
    labels:
      job: facial_recognition
      __path__: /logs/*log